version: '2.2'

services:
  tor_proxy:
    build: .
    image: fphammerle/tor-proxy
    ports:
    - '127.0.0.1:9050:9050/tcp'
    - '127.0.0.1:53:9053/udp'
    environment:
      SOCKS_TIMEOUT_SECONDS: 240
    security_opt: ['no-new-privileges']
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m
    #cap_add: [SYS_PTRACE]

# https://docs.docker.com/compose/compose-file/compose-file-v2/
